#!/usr/bin/env python3
"""Report generator — produce finding reports from vault data."""

import json
import argparse
import sys
from datetime import datetime
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
from vault_manager import load_index, search_findings, get_stats, VAULT_DIR


def generate_markdown(model: str = "", persistent_only: bool = False,
                      title: str = "Adversarial Assessment Report") -> str:
    """Generate a markdown report from vault findings."""
    stats = get_stats()
    findings = search_findings(model=model, persistent_only=persistent_only)

    lines = [
        f"# {title}",
        f"**Generated:** {datetime.now().isoformat()}",
        f"**Engagement:** AEGIS BREAK",
        f"**Operator:** Zelus",
        "",
        "---",
        "",
        "## Executive Summary",
        "",
        f"- **Total findings:** {len(findings)}",
        f"- **Persistent bypasses:** {sum(1 for f in findings if f.get('persistent'))}",
        f"- **Techniques cataloged:** {stats['techniques_cataloged']}",
        f"- **Models assessed:** {stats['models_tested']}",
        f"- **Average compliance rate:** {stats['avg_compliance_rate']:.0%}",
        "",
    ]

    # Severity breakdown
    severity_order = ["critical", "high", "medium", "low"]
    severity_counts = {s: sum(1 for f in findings if f.get("severity") == s) for s in severity_order}
    lines.append("### Severity Distribution")
    lines.append("")
    lines.append("| Severity | Count |")
    lines.append("|----------|-------|")
    for s in severity_order:
        if severity_counts[s]:
            lines.append(f"| {s.upper()} | {severity_counts[s]} |")
    lines.append("")

    # Findings by technique
    techniques = {}
    for f in findings:
        t = f["technique"]
        if t not in techniques:
            techniques[t] = []
        techniques[t].append(f)

    lines.append("---")
    lines.append("")
    lines.append("## Findings by Technique")
    lines.append("")

    for tech, tech_findings in sorted(techniques.items(), key=lambda x: -max(f["compliance_rate"] for f in x[1])):
        best_rate = max(f["compliance_rate"] for f in tech_findings)
        persistent_count = sum(1 for f in tech_findings if f.get("persistent"))

        lines.append(f"### {tech}")
        lines.append(f"**Best compliance rate:** {best_rate:.0%} | "
                      f"**Findings:** {len(tech_findings)} | "
                      f"**Persistent:** {persistent_count}")
        lines.append("")
        lines.append("| ID | Model | Rate | Samples | Persistent | Severity |")
        lines.append("|-----|-------|------|---------|-----------|----------|")

        for f in sorted(tech_findings, key=lambda x: -x["compliance_rate"]):
            p = "Yes" if f.get("persistent") else "No"
            lines.append(f"| {f['id']} | {f['model']} | {f['compliance_rate']:.0%} | "
                          f"{f['samples']} | {p} | {f.get('severity', 'medium')} |")
        lines.append("")

    # Persistent findings detail
    persistent = [f for f in findings if f.get("persistent")]
    if persistent:
        lines.append("---")
        lines.append("")
        lines.append("## Confirmed Persistent Bypasses")
        lines.append("")
        for f in sorted(persistent, key=lambda x: -x["compliance_rate"]):
            lines.append(f"### {f['id']} — {f['technique']}")
            lines.append(f"- **Model:** {f['model']}")
            lines.append(f"- **Compliance rate:** {f['compliance_rate']:.0%} ({f['samples']} samples)")
            lines.append(f"- **Severity:** {f.get('severity', 'medium').upper()}")
            lines.append(f"- **Prompt preview:** `{f['prompt_preview'][:100]}...`")
            if f.get("notes"):
                lines.append(f"- **Notes:** {f['notes']}")
            lines.append("")

    # Remediation
    lines.extend([
        "---",
        "",
        "## Remediation Recommendations",
        "",
        "Remediation priorities based on confirmed persistent bypasses:",
        "",
    ])

    for i, f in enumerate(persistent[:10], 1):
        lines.append(f"{i}. **{f['technique']}** (compliance: {f['compliance_rate']:.0%}) — "
                      f"Model `{f['model']}` consistently complies. "
                      f"Root cause analysis required for safety training gap.")

    if not persistent:
        lines.append("No persistent bypasses confirmed. Continue monitoring.")

    lines.extend([
        "",
        "---",
        "",
        f"*Report generated by Zelus research toolkit — {datetime.now().strftime('%Y-%m-%d %H:%M')}*",
    ])

    return "\n".join(lines)


def generate_json(model: str = "", persistent_only: bool = False) -> dict:
    """Generate structured JSON report."""
    stats = get_stats()
    findings = search_findings(model=model, persistent_only=persistent_only)
    return {
        "report_type": "adversarial_assessment",
        "engagement": "AEGIS BREAK",
        "operator": "Zelus",
        "generated": datetime.now().isoformat(),
        "stats": stats,
        "findings": findings,
    }


def main():
    parser = argparse.ArgumentParser(description="Generate assessment reports from vault")
    parser.add_argument("--format", choices=["markdown", "json"], default="markdown")
    parser.add_argument("--model", default="", help="Filter by model")
    parser.add_argument("--persistent", action="store_true", help="Persistent findings only")
    parser.add_argument("--title", default="Adversarial Assessment Report")
    parser.add_argument("--output", help="Output path (default: stdout)")
    args = parser.parse_args()

    if args.format == "markdown":
        report = generate_markdown(model=args.model, persistent_only=args.persistent, title=args.title)
    else:
        report = json.dumps(generate_json(model=args.model, persistent_only=args.persistent), indent=2, default=str)

    if args.output:
        Path(args.output).write_text(report)
        print(f"Report written to {args.output}")
    else:
        print(report)


if __name__ == "__main__":
    main()
